### ISSUE TITLE
[Critical] Uncaught Exception

### ISSUE THREAD

**Issue by cezhunter** [danielbuechele/goofy#373]
`Uncaught Exception:
TypeError: Cannot read property 'getPrimaryDisplay' of null
at App.creatWindow (Resources/app.asar/src/main.js:54:37)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)`

I believe this is the error that causes my computer to crash at a few times... Might be an OS issue. Regardless, if this can be fixed that would be greatly appreciated. App was running in the background and not in use when this occurred.

**Comment by Pere5troika** [comment]
I receive a similar error constantly on my mac. Pretty annoying, have to restart goofy to fix otherwise blank screen in app.

Uncaught Exception:
Error: Object has been destroyed
    at App.<anonymous> (/Applications/Goofy.app/Contents/Resources/app.asar/src/main.js:135:14)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)

**Comment by jklp** [comment]
Closing for now as can't replicate on v3.3.3.  Please reopen if still happens and can investigate
